// This file was generated. DO NOT edit manually.
// Use `npm run generate-data-cy` to update this file.

declare namespace DataCy {
    export type Value = 
        "accept-auth-provider-change-accept" |
        "accept-auth-provider-change-decline" |
        "accept-auth-provider-change-info-text" |
        "accept-invitation-accept" |
        "accept-invitation-decline" |
        "accept-invitation-email-mismatch" |
        "accept-invitation-info-text" |
        "account-security-initial-password-set" |
        "account-security-provider-connect" |
        "account-security-provider-disconnect" |
        "account-security-set-password-instructions-sent" |
        "activity-compact" |
        "activity-compact-detail-button" |
        "activity-detail" |
        "activity-detail-dialog" |
        "administration-access-message" |
        "administration-debug-customer-account-message" |
        "administration-debug-customer-exit-button" |
        "administration-frame" |
        "administration-organizations-list-item" |
        "administration-organizations-projects-button" |
        "administration-organizations-settings-button" |
        "administration-user-debug-account" |
        "administration-user-delete-user" |
        "administration-user-disable-user" |
        "administration-user-enable-user" |
        "administration-user-menu" |
        "administration-user-role-select" |
        "administration-users-list-item" |
        "agency-select" |
        "agency-select-item" |
        "ai-menu-context-data" |
        "ai-menu-prompts" |
        "ai-playground-preview" |
        "api-key-expiry-info" |
        "api-key-list-item" |
        "api-key-list-item-delete-button" |
        "api-key-list-item-description" |
        "api-key-list-item-last-used" |
        "api-key-list-item-new-token-input" |
        "api-key-list-item-regenerate-button" |
        "api-keys-create-edit-dialog" |
        "api-keys-project-select-item" |
        "auto-avatar-img" |
        "avatar-image" |
        "avatar-menu-open-button" |
        "avatar-remove-button" |
        "avatar-upload-button" |
        "avatar-upload-file-input" |
        "base-language-select" |
        "base-language-select-item" |
        "batch-operation-copy-source-select" |
        "batch-operation-copy-source-select-item" |
        "batch-operation-dialog-cancel-job" |
        "batch-operation-dialog-end-status" |
        "batch-operation-dialog-minimize" |
        "batch-operation-dialog-ok" |
        "batch-operation-dialog-view-trash" |
        "batch-operations-section" |
        "batch-operations-select" |
        "batch-operations-submit-button" |
        "batch-progress" |
        "batch-select-item" |
        "branch-default-chip" |
        "branch-select-item" |
        "branch-selector" |
        "cell-key-screenshot-dropzone" |
        "cell-key-screenshot-file-input" |
        "checkbox-group-multiselect" |
        "color-palette-field" |
        "color-palette-popover" |
        "color-preview" |
        "comment" |
        "comment-menu" |
        "comment-menu-delete" |
        "comment-menu-needs-resolution" |
        "comment-resolve" |
        "comment-text" |
        "content-delivery-add-button" |
        "content-delivery-auto-publish-checkbox" |
        "content-delivery-delete-button" |
        "content-delivery-files-button" |
        "content-delivery-form-branch" |
        "content-delivery-form-custom-slug" |
        "content-delivery-form-name" |
        "content-delivery-form-save" |
        "content-delivery-item-edit" |
        "content-delivery-item-publish" |
        "content-delivery-item-type" |
        "content-delivery-list-item" |
        "content-delivery-prune-before-publish-checkbox" |
        "content-delivery-published-file" |
        "content-delivery-storage-selector" |
        "content-delivery-storage-selector-item" |
        "content-delivery-subtitle" |
        "content-delivery-zip-export-checkbox" |
        "dashboard-projects-list-item" |
        "default-namespace-select" |
        "delete-user-button" |
        "developer-menu-content-delivery" |
        "developer-menu-storage" |
        "developer-menu-webhooks" |
        "disabled-feature-banner" |
        "dropzone" |
        "dropzone-inner" |
        "edit-pat-dialog-content" |
        "edit-pat-dialog-description-input" |
        "edit-pat-dialog-title" |
        "error-message" |
        "expiration-date-field" |
        "expiration-date-picker" |
        "expiration-select" |
        "export-escape_html-selector" |
        "export-format-selector" |
        "export-format-selector-item" |
        "export-language-selector" |
        "export-language-selector-item" |
        "export-message-format-selector" |
        "export-message-format-selector-item" |
        "export-namespace-selector" |
        "export-namespace-selector-item" |
        "export-state-selector" |
        "export-state-selector-item" |
        "export-submit-button" |
        "export-support_arrays-selector" |
        "file-dropzone-add-more-button" |
        "file-dropzone-remove-button" |
        "file-dropzone-select-button" |
        "filter-item" |
        "filter-item-exclude" |
        "former-user-name" |
        "generate-api-key-dialog-description-input" |
        "generate-pat-dialog-content" |
        "generate-pat-dialog-description-input" |
        "generate-pat-dialog-title" |
        "global-base-view-content" |
        "global-base-view-title" |
        "global-confirmation-cancel" |
        "global-confirmation-confirm" |
        "global-confirmation-dialog" |
        "global-confirmation-hard-mode-text-field" |
        "global-editor" |
        "global-empty-state" |
        "global-form-cancel-button" |
        "global-form-save-button" |
        "global-form-select" |
        "global-language-menu" |
        "global-list-items" |
        "global-list-pagination" |
        "global-list-search" |
        "global-loading" |
        "global-paginated-list" |
        "global-plus-button" |
        "global-search-field" |
        "global-user-menu-button" |
        "glossary-term-highlight" |
        "handlebars-editor" |
        "import-conflict-resolution-dialog" |
        "import-conflicts-not-resolved-dialog" |
        "import-conflicts-not-resolved-dialog-cancel-button" |
        "import-conflicts-not-resolved-dialog-resolve-button" |
        "import-file-error" |
        "import-file-error-collapse-button" |
        "import-file-error-more-less-button" |
        "import-file-input" |
        "import-file-issues-button" |
        "import-file-issues-dialog" |
        "import-file-warnings" |
        "import-override-key-descriptions-checkbox" |
        "import-progress" |
        "import-progress-overlay" |
        "import-resolution-dialog-accept-imported-button" |
        "import-resolution-dialog-accept-old-button" |
        "import-resolution-dialog-close-button" |
        "import-resolution-dialog-conflict-count" |
        "import-resolution-dialog-data-row" |
        "import-resolution-dialog-existing-translation" |
        "import-resolution-dialog-key-name" |
        "import-resolution-dialog-new-translation" |
        "import-resolution-dialog-resolved-count" |
        "import-resolution-dialog-show-resolved-switch" |
        "import-resolution-dialog-translation-check" |
        "import-resolution-dialog-translation-loading" |
        "import-resolution-translation-expand-button" |
        "import-result-delete-language-button" |
        "import-result-file-cell" |
        "import-result-file-warnings" |
        "import-result-language-menu-cell" |
        "import-result-namespace-cell" |
        "import-result-resolve-button" |
        "import-result-resolved-conflicts-cell" |
        "import-result-row" |
        "import-result-show-all-translations-button" |
        "import-result-total-count-cell" |
        "import-row-language-select-clear-button" |
        "import-row-language-select-form-control" |
        "import-show-data-dialog" |
        "import_apply_import_button" |
        "import_cancel_import_button" |
        "integrate-api-key-selector-create-new-item" |
        "integrate-api-key-selector-item" |
        "integrate-api-key-selector-select" |
        "integrate-api-key-selector-select-input" |
        "integrate-choose-your-weapon-step-content" |
        "integrate-choose-your-weapon-step-label" |
        "integrate-go-to-docs-button" |
        "integrate-guide" |
        "integrate-select-api-key-step-content" |
        "integrate-select-api-key-step-label" |
        "integrate-weapon-selector-button" |
        "invitation-accepted-success-message" |
        "invitation-dialog-close-button" |
        "invitation-dialog-input-field" |
        "invitation-dialog-invite-button" |
        "invitation-dialog-role-button" |
        "invitation-dialog-type-agency-button" |
        "invitation-dialog-type-email-button" |
        "invitation-dialog-type-link-button" |
        "invitation_email_mismatch_message" |
        "invite-generate-button" |
        "key-char-limit-checkbox" |
        "key-char-limit-input" |
        "key-edit-tab-advanced" |
        "key-edit-tab-context" |
        "key-edit-tab-custom-properties" |
        "key-edit-tab-general" |
        "key-plural-checkbox" |
        "key-plural-variable-name" |
        "label-autocomplete-option" |
        "label-selector-autocomplete" |
        "language-delete-button" |
        "language-icon-list-item" |
        "language-modify-form" |
        "languages-add-dialog-submit" |
        "languages-create-autocomplete-field" |
        "languages-create-autocomplete-suggested-option" |
        "languages-create-cancel-prepared-button" |
        "languages-create-customize-button" |
        "languages-flag-selector-open-button" |
        "languages-menu-machine-translation" |
        "languages-menu-project-languages" |
        "languages-modify-apply-button" |
        "languages-modify-cancel-button" |
        "languages-prepared-language-box" |
        "llm-machine-translation-customize" |
        "login-button" |
        "login-provider" |
        "machine-translations-settings-language-enabled-service" |
        "machine-translations-settings-language-options" |
        "machine-translations-settings-language-primary-service" |
        "mfa-disable-button" |
        "mfa-disable-dialog" |
        "mfa-disable-dialog-content" |
        "mfa-disable-dialog-password-input" |
        "mfa-disable-dialog-title" |
        "mfa-enable-button" |
        "mfa-enable-dialog" |
        "mfa-enable-dialog-content" |
        "mfa-enable-dialog-otp-input" |
        "mfa-enable-dialog-password-input" |
        "mfa-enable-dialog-title" |
        "mfa-enable-dialog-totp-key" |
        "mfa-recovery-button" |
        "mfa-recovery-codes-dialog" |
        "mfa-recovery-codes-dialog-close" |
        "mfa-recovery-codes-dialog-content" |
        "mfa-recovery-codes-dialog-password-input" |
        "mfa-recovery-codes-dialog-title" |
        "mt-admin-access-info" |
        "mt-language-dialog-auto-for-import" |
        "mt-language-dialog-auto-machine-translation" |
        "mt-language-dialog-auto-translation-memory" |
        "mt-language-dialog-enabled-checkbox" |
        "mt-language-dialog-formality-select" |
        "mt-language-dialog-formality-select-item" |
        "mt-language-dialog-primary-radio" |
        "mt-language-dialog-save" |
        "mt-language-dialog-service-label" |
        "namespace-value" |
        "namespaces-banner-content" |
        "namespaces-banner-menu" |
        "namespaces-banner-menu-button" |
        "namespaces-banner-menu-option" |
        "namespaces-rename-cancel" |
        "namespaces-rename-confirm" |
        "namespaces-rename-text-field" |
        "namespaces-select-cancel" |
        "namespaces-select-confirm" |
        "namespaces-select-text-field" |
        "namespaces-selector" |
        "navigation-item" |
        "notifications-button" |
        "notifications-count" |
        "notifications-empty-message" |
        "notifications-list" |
        "notifications-list-item" |
        "notifications-settings-icon" |
        "notistack-snackbar" |
        "organization-address-part-field" |
        "organization-description-field" |
        "organization-invitation-cancel-button" |
        "organization-invitation-copy-button" |
        "organization-invitation-item" |
        "organization-member-item" |
        "organization-member-leave-button" |
        "organization-members-remove-user-button" |
        "organization-name-field" |
        "organization-profile" |
        "organization-profile-delete-button" |
        "organization-profile-leave-button" |
        "organization-role-menu" |
        "organization-role-menu-button" |
        "organization-role-select-item" |
        "organization-side-menu" |
        "organization-switch" |
        "palette-color" |
        "pat-expiry-info" |
        "pat-list-item" |
        "pat-list-item-alert" |
        "pat-list-item-delete-button" |
        "pat-list-item-description" |
        "pat-list-item-last-used" |
        "pat-list-item-new-token-input" |
        "pat-list-item-regenerate-button" |
        "pending-invitation-banner" |
        "pending-invitation-dismiss" |
        "permissions-advanced-checkbox" |
        "permissions-advanced-item" |
        "permissions-language-menu-button" |
        "permissions-menu" |
        "permissions-menu-basic" |
        "permissions-menu-button" |
        "permissions-menu-close" |
        "permissions-menu-granular" |
        "permissions-menu-inherited-message" |
        "permissions-menu-reset-to-organization" |
        "permissions-menu-save" |
        "plan_seat_limit_exceeded_while_accepting_invitation_message" |
        "project-base-language-tm-conflict-confirm" |
        "project-base-language-tm-conflict-dialog" |
        "project-base-language-tm-conflict-list" |
        "project-dashboard-activity-chart" |
        "project-dashboard-activity-list" |
        "project-dashboard-base-word-count" |
        "project-dashboard-description" |
        "project-dashboard-key-count" |
        "project-dashboard-language-bar" |
        "project-dashboard-language-count" |
        "project-dashboard-language-label-keys" |
        "project-dashboard-language-label-percentage" |
        "project-dashboard-language-label-state" |
        "project-dashboard-language-label-words" |
        "project-dashboard-language-menu" |
        "project-dashboard-language-menu-export" |
        "project-dashboard-language-menu-settings" |
        "project-dashboard-languages-edit" |
        "project-dashboard-members" |
        "project-dashboard-members-count" |
        "project-dashboard-progress" |
        "project-dashboard-project-totals" |
        "project-dashboard-reviewed-percentage" |
        "project-dashboard-strings" |
        "project-dashboard-strings-count" |
        "project-dashboard-tags" |
        "project-dashboard-task-count" |
        "project-dashboard-text" |
        "project-dashboard-translated-percentage" |
        "project-delete-button" |
        "project-leave-button" |
        "project-list-languages" |
        "project-list-more-button" |
        "project-list-qa-badge-button" |
        "project-list-translations-button" |
        "project-member-item" |
        "project-member-revoke-button" |
        "project-members-invitation-item" |
        "project-menu-item" |
        "project-menu-item-ai" |
        "project-menu-item-branches" |
        "project-menu-item-dashboard" |
        "project-menu-item-developer" |
        "project-menu-item-export" |
        "project-menu-item-import" |
        "project-menu-item-integrate" |
        "project-menu-item-languages" |
        "project-menu-item-members" |
        "project-menu-item-projects" |
        "project-menu-item-settings" |
        "project-menu-item-tasks" |
        "project-menu-item-translations" |
        "project-menu-items" |
        "project-mt-dialog-settings-inherited" |
        "project-name-field" |
        "project-select" |
        "project-settings" |
        "project-settings-button" |
        "project-settings-delete-button" |
        "project-settings-description" |
        "project-settings-languages" |
        "project-settings-languages-add" |
        "project-settings-languages-list-edit-button" |
        "project-settings-languages-list-name" |
        "project-settings-menu-advanced" |
        "project-settings-menu-general" |
        "project-settings-menu-labels" |
        "project-settings-menu-qa" |
        "project-settings-name" |
        "project-settings-suggestions-mode-switch" |
        "project-settings-transfer-button" |
        "project-settings-translation-protection-switch" |
        "project-settings-use-branching-switch" |
        "project-settings-use-namespaces-default-namespace-select" |
        "project-settings-use-namespaces-switch" |
        "project-settings-use-tolgee-placeholders-switch" |
        "project-states-bar-bar" |
        "project-states-bar-dot" |
        "project-states-bar-legend" |
        "project-states-bar-root" |
        "project-states-bar-state-progress" |
        "project-transfer-autocomplete-field" |
        "project-transfer-autocomplete-suggested-option" |
        "project-transfer-confirmation-field" |
        "project-transfer-dialog" |
        "quick-start-action" |
        "quick-start-dialog" |
        "quick-start-finish-action" |
        "quick-start-finish-step" |
        "quick-start-highlight" |
        "quick-start-highlight-ok" |
        "quick-start-step" |
        "regenerate-pat-dialog-content" |
        "regenerate-pat-dialog-title" |
        "resend-email-button" |
        "screenshot-image" |
        "screenshot-thumbnail" |
        "screenshot-thumbnail-delete" |
        "search-select" |
        "search-select-item" |
        "search-select-new" |
        "search-select-search" |
        "seat_spending_limit_exceeded_while_accepting_invitation_message" |
        "sensitive-dialog-otp-input" |
        "sensitive-dialog-password-input" |
        "sensitive-protection-dialog" |
        "settings-menu-item" |
        "sign-up-submit-button" |
        "signup-error-free-seat-limit" |
        "signup-error-plan-seat-limit" |
        "signup-error-seats-spending-limit" |
        "sso-migration-info-text" |
        "submenu-item" |
        "suggestion-action" |
        "suggestions-list" |
        "switch-popover-item" |
        "switch-popover-new" |
        "switch-popover-search" |
        "tag-autocomplete-input" |
        "tag-autocomplete-option" |
        "task-state" |
        "this-is-the-element" |
        "top-banner" |
        "top-banner-content" |
        "top-banner-dismiss-button" |
        "transfer-project-apply-button" |
        "translation-controls-sort" |
        "translation-controls-sort-item" |
        "translation-create-description-input" |
        "translation-create-key-input" |
        "translation-create-namespace-input" |
        "translation-create-translation-input" |
        "translation-edit-delete-button" |
        "translation-edit-key-field" |
        "translation-edit-translation-field" |
        "translation-editor" |
        "translation-field-label" |
        "translation-history-item" |
        "translation-label" |
        "translation-label-add" |
        "translation-label-control" |
        "translation-label-delete" |
        "translation-panel" |
        "translation-panel-content" |
        "translation-panel-items-count" |
        "translation-panel-toggle" |
        "translation-plural-parameter" |
        "translation-plural-variant" |
        "translation-state-button" |
        "translation-suggestion" |
        "translation-suggestion-action-menu-item" |
        "translation-text" |
        "translation-tools-machine-translation-item" |
        "translation-tools-machine-translation-item-prompt" |
        "translation-tools-suggestions-show-all-checkbox" |
        "translation-tools-translation-memory-empty" |
        "translation-tools-translation-memory-item" |
        "translation-tools-translation-memory-item-key-name" |
        "translation-tools-translation-memory-item-score" |
        "translation-tools-translation-memory-item-tm-name" |
        "translation-tools-translation-memory-item-updated" |
        "translations-add-button" |
        "translations-auto-translated-clear-button" |
        "translations-auto-translated-indicator" |
        "translations-cell-cancel-button" |
        "translations-cell-comments-button" |
        "translations-cell-edit-button" |
        "translations-cell-insert-base-button" |
        "translations-cell-main-action-button" |
        "translations-cell-menu-item" |
        "translations-cell-menu-open-button" |
        "translations-cell-qa-issues-button" |
        "translations-cell-screenshots-button" |
        "translations-cell-switch-mode" |
        "translations-cell-task-button" |
        "translations-comments-input" |
        "translations-comments-load-more-button" |
        "translations-filter-apply-for-all" |
        "translations-filter-apply-for-expand" |
        "translations-filter-apply-for-language" |
        "translations-filter-apply-no-base" |
        "translations-filter-select" |
        "translations-filter-select-clear" |
        "translations-history-load-more-button" |
        "translations-key-cell-description" |
        "translations-key-count" |
        "translations-key-edit-description-field" |
        "translations-key-edit-key-field" |
        "translations-key-name" |
        "translations-language-select-all" |
        "translations-language-select-form-control" |
        "translations-language-select-item" |
        "translations-language-select-none" |
        "translations-namespace-banner" |
        "translations-outdated-clear-button" |
        "translations-outdated-indicator" |
        "translations-row" |
        "translations-row-checkbox" |
        "translations-select-all-button" |
        "translations-shortcuts-command" |
        "translations-state-indicator" |
        "translations-table-cell" |
        "translations-table-cell-language" |
        "translations-table-cell-translation" |
        "translations-tag" |
        "translations-tag-add" |
        "translations-tag-close" |
        "translations-tag-input" |
        "translations-tags-add" |
        "translations-toolbar-counter" |
        "translations-toolbar-to-top" |
        "translations-trash-button" |
        "translations-view-list" |
        "translations-view-list-button" |
        "translations-view-table" |
        "translations-view-table-button" |
        "trash-banner-close" |
        "trash-batch-bar" |
        "trash-batch-select" |
        "trash-batch-select-item" |
        "trash-permanent-delete-button" |
        "trash-restore-button" |
        "trash-row" |
        "trash-row-checkbox" |
        "trash-select-all" |
        "trash-select-all-header" |
        "trash-sort-button" |
        "trash-table" |
        "user-delete-organization-message-item" |
        "user-menu-language-switch" |
        "user-menu-logout" |
        "user-menu-my-tasks" |
        "user-menu-organization-settings" |
        "user-menu-organization-switch" |
        "user-menu-server-administration" |
        "user-menu-theme-switch" |
        "user-menu-user-settings" |
        "user-profile" |
        "user-switch-item" |
        "user-switch-search"
}
